import { normaliseProfile } from './src/domain/finance.mjs';
import { identifyOpportunities } from './src/engine/opportunities.mjs';

const key = 'spendmap-profile-v1';
const defaults = { incomes:[{name:'Salary',amount:3200,frequency:'fortnightly'}],expenses:[{name:'Rent',category:'housing',amount:1900,frequency:'monthly'},{name:'Groceries',category:'groceries',amount:220,frequency:'weekly'},{name:'Mobile plan',category:'mobile',amount:69,frequency:'monthly'},{name:'Home internet',category:'internet',amount:95,frequency:'monthly'}]};
const catalogue=[{category:'mobile',name:'Comparable SIM-only plan',monthlyCost:35,confidence:'estimate',source:'Spendmap example catalogue',caveats:['Coverage, data allowance and regional availability vary.']},{category:'internet',name:'Comparable NBN plan',monthlyCost:75,confidence:'estimate',source:'Spendmap example catalogue',caveats:['Check technology type, speed tier and introductory pricing.']},{category:'energy',name:'Comparable energy offer',monthlyCost:130,confidence:'estimate',source:'Spendmap example catalogue',caveats:['Requires postcode, tariff and usage comparison.']}];
let profile=JSON.parse(localStorage.getItem(key)||'null')||defaults;
const money=v=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(v);
function save(){localStorage.setItem(key,JSON.stringify(profile));render()}
function remove(kind,i){profile[kind].splice(i,1);save()}
function list(kind,id){document.querySelector(id).innerHTML=profile[kind].map((x,i)=>`<li><span>${x.name} <small>· ${money(x.amount)} ${x.frequency}</small></span><button aria-label="Remove ${x.name}" data-remove="${kind}:${i}">×</button></li>`).join('')||'<li>No entries yet</li>'}
function render(){const plan=normaliseProfile(profile);document.querySelector('#income').textContent=money(plan.monthlyIncome);document.querySelector('#expenses').textContent=money(plan.monthlyExpenses);document.querySelector('#surplus').textContent=money(plan.monthlySurplus);document.querySelector('#surplus-copy').textContent=plan.monthlySurplus>=0?'available after entered expenses':'more commitments than income';list('incomes','#income-list');list('expenses','#expense-list');const cats=Object.entries(plan.expenses.reduce((o,x)=>(o[x.category]=(o[x.category]||0)+x.monthlyAmount,o),{})).sort((a,b)=>b[1]-a[1]);const max=cats[0]?.[1]||1;document.querySelector('#categories').innerHTML=cats.map(([name,value])=>`<div><div class="bar-head"><span>${name}</span><strong>${money(value)}</strong></div><div class="track"><i style="width:${value/max*100}%"></i></div></div>`).join('')||'<p>No expenses entered.</p>';document.querySelector('#forecast').innerHTML=[['Income per fortnight',plan.monthlyIncome/26*12],['Commitments per fortnight',plan.monthlyExpenses/26*12],['Room to move',plan.monthlySurplus/26*12]].map(([a,b])=>`<div class="cycle"><span>${a}</span><strong>${money(b)}</strong></div>`).join('');const opportunities=identifyOpportunities(profile.expenses,catalogue);document.querySelector('#opportunities').innerHTML=opportunities.length?opportunities.map(x=>`<article class="opportunity"><p class="eyebrow">${x.category} · ${x.confidence}</p><h3>${x.category[0].toUpperCase()+x.category.slice(1)}</h3><strong>${money(x.monthlySaving)}/mo</strong><p>${x.rationale}</p><small>Source: ${x.source}. ${x.caveats.join(' ')}</small></article>`).join(''):'<article class="opportunity"><h3>No clear comparison yet</h3><p>Add mobile, internet or energy costs to see catalogue-based examples.</p></article>'}
for(const [form,kind] of [['#income-form','incomes'],['#expense-form','expenses']])document.querySelector(form).addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));profile[kind].push({...d,amount:Number(d.amount)});e.currentTarget.reset();save()});document.addEventListener('click',e=>{const v=e.target.dataset.remove;if(v){const[kind,i]=v.split(':');remove(kind,Number(i))}});document.querySelector('#reset').onclick=()=>{profile=structuredClone(defaults);save()};render();
