import { startAuthentication, startRegistration } from './vendor/simplewebauthn/index.js';

const root = document.querySelector('#auth-root');
const account = document.querySelector('#account');
const request = async (url, options = {}) => {
  const response = await fetch(url, { credentials: 'same-origin', headers: { 'content-type': 'application/json', ...(options.headers || {}) }, ...options });
  const data = response.status === 204 ? {} : await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Something went wrong.');
  return data;
};
const esc = value => String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const close = () => { root.innerHTML = ''; };
const show = html => { root.innerHTML = `<div class="auth-shade" role="presentation"><section class="auth-card" role="dialog" aria-modal="true">${html}</section></div>`; root.querySelector('.auth-shade').addEventListener('click', event => { if (event.target === event.currentTarget) close(); }); };
function message(error = '') { return `<p class="auth-error" aria-live="polite">${esc(error)}</p>`; }
function bindForm(selector, fn) { root.querySelector(selector)?.addEventListener('submit', async event => { event.preventDefault(); const button = event.currentTarget.querySelector('button[type="submit"]'); button.disabled = true; try { await fn(Object.fromEntries(new FormData(event.currentTarget))); } catch (error) { const target = root.querySelector('.auth-error'); target.textContent = error.message; button.disabled = false; } }); }
function authView(mode = 'signin', error = '') {
  show(`<button class="auth-close" aria-label="Close">×</button><p class="eyebrow">PRIVATE, ON YOUR TERMS</p><h2>${mode === 'signup' ? 'Create your Spendmap account' : 'Welcome back'}</h2><p class="auth-copy">Use a password, then add a passkey or authenticator app from account security.</p>${message(error)}<form id="password-form" class="auth-form"><label>Email<input name="email" type="email" autocomplete="email" required /></label><label>Password<input name="password" type="password" ${mode === 'signup' ? 'autocomplete="new-password" minlength="12"' : 'autocomplete="current-password"'} required /></label><button type="submit">${mode === 'signup' ? 'Create account' : 'Sign in'}</button></form><div class="auth-divider"><span>or</span></div><form id="passkey-form" class="auth-form compact"><label>Email for passkey<input name="email" type="email" autocomplete="email webauthn" required /></label><button type="submit" class="outline">Use a passkey</button></form><p class="auth-switch">${mode === 'signup' ? 'Already have an account?' : 'New to Spendmap?'} <button id="switch-auth" class="link-button">${mode === 'signup' ? 'Sign in' : 'Create one'}</button></p>`);
  root.querySelector('.auth-close').onclick = close;
  root.querySelector('#switch-auth').onclick = () => authView(mode === 'signup' ? 'signin' : 'signup');
  bindForm('#password-form', async values => { const data = await request(`/api/auth/${mode}`, { method: 'POST', body: JSON.stringify(values) }); if (data.user.mfaPending) return totpLogin(); await refresh(); close(); });
  bindForm('#passkey-form', async values => { const options = await request('/api/auth/passkey/authenticate/options', { method: 'POST', body: JSON.stringify(values) }); const credential = await startAuthentication({ optionsJSON: options }); await request('/api/auth/passkey/authenticate/verify', { method: 'POST', body: JSON.stringify({ credential }) }); await refresh(); close(); });
}
function totpLogin(error = '') { show(`<button class="auth-close" aria-label="Close">×</button><p class="eyebrow">ONE MORE STEP</p><h2>Enter your authenticator code</h2><p class="auth-copy">Your password was accepted. Enter the current six-digit code from your authenticator app.</p>${message(error)}<form id="totp-login" class="auth-form"><label>Authenticator code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required /></label><button type="submit">Verify and sign in</button></form>`); root.querySelector('.auth-close').onclick = close; bindForm('#totp-login', async values => { await request('/api/auth/totp/verify-login', { method: 'POST', body: JSON.stringify(values) }); await refresh(); close(); }); }
async function securityView(user) {
  const keys = await request('/api/auth/passkeys');
  show(`<button class="auth-close" aria-label="Close">×</button><p class="eyebrow">ACCOUNT SECURITY</p><h2>${esc(user.email)}</h2><p class="auth-copy">Add a phishing-resistant passkey and, if you want a separate second factor for password sign-in, an authenticator app.</p><div class="security-row"><div><strong>Passkeys</strong><small>${keys.passkeys.length ? `${keys.passkeys.length} registered` : 'No passkey registered'}</small></div><button id="add-passkey" class="outline">Add passkey</button></div>${keys.passkeys.map(key => `<div class="key-row"><span>${esc(key.name)}</span><button class="link-button remove-key" data-key="${esc(key.id)}">Remove</button></div>`).join('')}<div class="security-row"><div><strong>Authenticator app</strong><small>${user.totpEnabled ? 'Enabled for password sign-in' : 'Optional second factor'}</small></div><button id="totp-action" class="outline">${user.totpEnabled ? 'Disable' : 'Set up'}</button></div><button id="signout" class="danger">Sign out</button>`);
  root.querySelector('.auth-close').onclick = close;
  root.querySelector('#add-passkey').onclick = async () => { try { const options = await request('/api/auth/passkey/register/options', { method: 'POST', body: '{}' }); const credential = await startRegistration({ optionsJSON: options }); await request('/api/auth/passkey/register/verify', { method: 'POST', body: JSON.stringify({ credential, name: 'My passkey' }) }); await securityView(user); } catch (error) { alert(error.message); } };
  root.querySelectorAll('.remove-key').forEach(button => button.onclick = async () => { await request(`/api/auth/passkeys/${button.dataset.key}`, { method: 'DELETE', body: '{}' }); await securityView(user); });
  root.querySelector('#totp-action').onclick = async () => { if (user.totpEnabled) { await request('/api/auth/totp/disable', { method: 'POST', body: '{}' }); user.totpEnabled = false; return securityView(user); } const setup = await request('/api/auth/totp/setup', { method: 'POST', body: '{}' }); totpSetup(setup); };
  root.querySelector('#signout').onclick = async () => { await request('/api/auth/signout', { method: 'POST', body: '{}' }); await refresh(); close(); };
}
function totpSetup(setup, error = '') { show(`<button class="auth-close" aria-label="Close">×</button><p class="eyebrow">AUTHENTICATOR APP</p><h2>Set up two-factor authentication</h2><p class="auth-copy">Scan this QR code in your authenticator app, then enter its current code. Keep the secret private.</p><img class="totp-qr" src="${setup.qrCode}" alt="QR code for Spendmap authenticator setup"/><details><summary>Can’t scan it?</summary><code>${esc(setup.secret)}</code></details>${message(error)}<form id="totp-enable" class="auth-form"><label>Six-digit code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required /></label><button type="submit">Enable two-factor authentication</button></form>`); root.querySelector('.auth-close').onclick = close; bindForm('#totp-enable', async values => { await request('/api/auth/totp/enable', { method: 'POST', body: JSON.stringify(values) }); await refresh(); close(); }); }
async function refresh() { const { user } = await request('/api/auth/me'); account.textContent = user ? 'Account' : 'Sign in'; account.onclick = () => user ? securityView(user).catch(error => authView('signin', error.message)) : authView(); }
refresh().catch(() => { account.onclick = () => authView(); });
